# Generated by Django 3.1 on 2020-08-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='owner',
            new_name='user',
        ),
    ]
